[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "vespwood"
version = "1.0.1"
description = "Declarative framework for LLMs"
license = {text = "Apache"}
readme = "README.md"
requires-python = ">=3.12.0,<4.0.0"
dependencies = []

[project.optional-dependencies]
yaml = [
    "PyYAML"
]

[project.urls]
Homepage = "https://vespwood.com"
Repository = "https://github.com/ayush-suman/vesp.git"

