[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "vesp"
version = "1.0.0"
description = "Declarative framework for agents"
license = {text = "Apache"}
readme = "README.md"
requires-python = ">=3.12.0,<4.0.0"
dependencies = [
    "vespwood"
]

[project.optional-dependencies]
yaml = [
    "vespwood[yaml]"
]

openai = [
    "vespwood-openai"
]

anthropic = [
    "vespwood-anthropic"
]

[project.urls]
Homepage = "https://vespwood.com"
Repository = "https://github.com/ayush-suman/vesp.git"

[tool.uv.sources]
vespwood = { workspace = true }
vespwood-openai = { workspace = true }
vespwood-anthropic = {workspace = true }

